### ISSUE TITLE
ninja -v -j4 failed

### ISSUE THREAD

**Issue by dreamqin68** [secure-foundations/veri-titan#75]
After running `ninja -v -j4`, the output is following

```
[1/229] ./tools/vale/bin/vale -dafnyText -in arch/otbn/msp430/decls.i.vad -out gen/arch/otbn/msp430/decls.i.dfy
FAILED: gen/arch/otbn/msp430/decls.i.dfy
./tools/vale/bin/vale -dafnyText -in arch/otbn/msp430/decls.i.vad -out gen/arch/otbn/msp430/decls.i.dfy

error:
System.MissingMethodException: Method not found: 'System.String System.String.TrimEnd()'.
   at Main.main(String[] argv)
[2/229] ./tools/vale/bin/vale -dafnyText -in arch/riscv/decls.i.vad -out gen/arch/riscv/decls.i.dfy
FAILED: gen/arch/riscv/decls.i.dfy
./tools/vale/bin/vale -dafnyText -in arch/riscv/decls.i.vad -out gen/arch/riscv/decls.i.dfy

error:
System.MissingMethodException: Method not found: 'System.String System.String.TrimEnd()'.
   at Main.main(String[] argv)
[3/229] ./tools/vale/bin/vale -dafnyText -in arch/otbn/decls.i.vad -out gen/arch/otbn/decls.i.dfy
FAILED: gen/arch/otbn/decls.i.dfy
./tools/vale/bin/vale -dafnyText -in arch/otbn/decls.i.vad -out gen/arch/otbn/decls.i.dfy

error:
System.MissingMethodException: Method not found: 'System.String System.String.TrimEnd()'.
   at Main.main(String[] argv)
[4/229] ./tools/vale/bin/vale -dafnyText -in arch/msp430/decls.i.vad -out gen/arch/msp430/decls.i.dfy
FAILED: gen/arch/msp430/decls.i.dfy
./tools/vale/bin/vale -dafnyText -in arch/msp430/decls.i.vad -out gen/arch/msp430/decls.i.dfy

error:
System.MissingMethodException: Method not found: 'System.String System.String.TrimEnd()'.
   at Main.main(String[] argv)
ninja: build stopped: subcommand failed.
```
How to fix it? Thanks!

**Comment by yizhou7** [comment]
Can you give the dotnet version you are using? I realize that the link in the repo points to 6.0, but personally I have been using 5.0.

**Comment by dreamqin68** [comment]
The version of my dotnet version is 6.0. After changing it to 5.0, the previous error no longer occurs. Thanks!

Then I ran into another problem after `ninja -v -j4`
```
[2/168] python3 build.py dd-gen arch/otbn/msp430/machine.s.dfy gen/arch/otbn/msp430/machine.s.dd
ninja: build stopped: 'gen/arch/lib/bv16_ops.ver', needed by 'gen/arch/otbn/msp430/machine.s.ver', missing and no known rule to make it.
```

**Comment by yizhou7** [comment]
thanks for bringing it up! it appears that there are some spurious files in the repo. i have removed them so hopefully it works now.

**Comment by dreamqin68** [comment]
Thanks!  After the update, I had another problem.

```
[91/218] ./tools/dafny/Binaries/Dafny /compile:0 /noNLarith /timeLimit:20 /vcsCores:4 lib/generic_mm_lemmas.dfy && touch gen/lib/generic_mm_lemmas.ver
FAILED: gen/lib/generic_mm_lemmas.ver
./tools/dafny/Binaries/Dafny /compile:0 /noNLarith /timeLimit:20 /vcsCores:4 lib/generic_mm_lemmas.dfy && touch gen/lib/generic_mm_lemmas.ver
Unhandled exception. System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Dafny.SingularDriver.RunSingular(String query) in /home/guest/veri-titan/tools/dafny/Source/Dafny/Translator.cs:line 312
   at Microsoft.Dafny.SingularDriver..ctor(Statement stmt) in /home/guest/veri-titan/tools/dafny/Source/Dafny/Translator.cs:line 347
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /home/guest/veri-titan/tools/dafny/Source/Dafny/Translator.cs:line 10607
   at Microsoft.Dafny.Translator.TrStmtList(List`1 stmts, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /home/guest/veri-titan/tools/dafny/Source/Dafny/Translator.cs:line 11443
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /home/guest/veri-titan/tools/dafny/Source/Dafny/Translator.cs:line 10984
   at Microsoft.Dafny.Translator.AddMethodImpl(Method m, Procedure proc, Boolean wellformednessProc) in /home/guest/veri-titan/tools/dafny/Source/Dafny/Translator.cs:line 4830
   at Microsoft.Dafny.Translator.AddMethod_Top(Method m) in /home/guest/veri-titan/tools/dafny/Source/Dafny/Translator.cs:line 2677
   at Microsoft.Dafny.Translator.AddClassMembers(TopLevelDeclWithMembers c, Boolean includeMethods) in /home/guest/veri-titan/tools/dafny/Source/Dafny/Translator.cs:line 2597
   at Microsoft.Dafny.Translator.AddTypeDecl(RevealableTypeDecl d) in /home/guest/veri-titan/tools/dafny/Source/Dafny/Translator.cs:line 1526
   at Microsoft.Dafny.Translator.DoTranslation(Program p, ModuleDefinition forModule) in /home/guest/veri-titan/tools/dafny/Source/Dafny/Translator.cs:line 1088
   at Microsoft.Dafny.Translator.Translate(Program p, ErrorReporter reporter, TranslatorFlags flags)+MoveNext() in /home/guest/veri-titan/tools/dafny/Source/Dafny/Translator.cs:line 1159
   at Microsoft.Dafny.DafnyDriver.Translate(Program dafnyProgram)+MoveNext() in /home/guest/veri-titan/tools/dafny/Source/DafnyDriver/DafnyDriver.cs:line 302
   at Microsoft.Dafny.DafnyDriver.Boogie(String baseName, IEnumerable`1 boogiePrograms, String programId, Dictionary`2& statss, PipelineOutcome& oc) in /home/guest/veri-titan/tools/dafny/Source/DafnyDriver/DafnyDriver.cs:line 352
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /home/guest/veri-titan/tools/dafny/Source/DafnyDriver/DafnyDriver.cs:line 277
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /home/guest/veri-titan/tools/dafny/Source/DafnyDriver/DafnyDriver.cs:line 60
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass1_0.<Main>b__0() in /home/guest/veri-titan/tools/dafny/Source/DafnyDriver/DafnyDriver.cs:line 36
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Aborted
```

**Comment by parno** [comment]
Have you installed [Singular](https://www.singular.uni-kl.de/)?  If so is it on your PATH?

**Comment by dreamqin68** [comment]
Thanks! After I specified the path, I didn't have the previous problem, and then I encountered the next problem.

```
[42/125] ./tools/dafny/Binaries/Dafny /compile:0 /noNLarith /timeLimit:20 /vcsCores:4 lib/falcon/mq_polys.dfy && touch gen/lib/falcon/mq_polys.ver
FAILED: gen/lib/falcon/mq_polys.ver
./tools/dafny/Binaries/Dafny /compile:0 /noNLarith /timeLimit:20 /vcsCores:4 lib/falcon/mq_polys.dfy && touch gen/lib/falcon/mq_polys.ver
/home/huan/veri-titan/lib/falcon/mq_polys.dfy(467,7): Verification of 'Impl$$mq__polys.__default.make__all__pairs__helper__result' timed out after 20 seconds

Dafny program verifier finished with 67 verified, 0 errors, 1 time out
```

**Comment by yizhou7** [comment]
It seems like there is a timeout on the proof. That might happen if the cores on the system are all too busy. One thing you can try is rerun ninja with a single core, so `ninja -v -j1`.

**Comment by dreamqin68** [comment]
Yeah, after running `ninja -v -j1`, it finally succeeded! Thanks!
